### ISSUE TITLE
mobx.makeObservable is not a function?

### ISSUE THREAD

**Issue by nickperkinslondon** [mobxjs/mobx-utils#281]
```
{ createViewModel } = require 'mobx-utils'	

thing = mobx.observable({
    attr:'value'
})

vm = createViewModel(thing)

```
TypeError: mobx.makeObservable is not a function
    at new ViewModel (D:\Dropbox\workspace\npl\node_modules\mobx-utils\mobx-utils.umd.js:633:18)
    at createViewModel (D:\Dropbox\workspace\npl\node_modules\mobx-utils\mobx-utils.umd.js:779:16)

**Comment by nickperkinslondon** [comment]
$ npm view mobx version
6.0.1
$ npm view mobx-utils version
6.0.1

**Comment by mweststrate** [comment]
This is most likely a problem with your local node_modules or project
setup. Not much we can do here, unless you can provide a
minimal reproduction, in which most probably the issue won't occur at all.

**Comment by yaarams** [comment]
I get this warning:
WARNING in ../node_modules/mobx-utils/mobx-utils.module.js 629:8-22
"export 'makeObservable' was not found in 'mobx'
mobx: 5.15.4
mobx-utils: 6.0.1

**Comment by mweststrate** [comment]
Please update to MobX 6, and respect peer dependency warnings when running
yarn / npm install :)
